import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-100 p-2">
        <h1 className="text-lg font-bold">NextShop</h1>
        <p>jinbinson</p>
        <p>-TailwindCss</p>
        <p>-MongDB</p>
      </div>
    </div>
  );
}
